spring:
  profiles:
    active: dev
  application:
    name: friends-gathering-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/friendsgathering?serverTimezone=UTC
    username: root
    password: 1234
  mvc:
    pathmatch:
      #Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher 解决knife4j匹配boot2.6.4 boot版本过高的问题
      matching-strategy: ant_path_matcher
  # springdoc-openapi项目配置
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      tags-sorter: alpha
      operations-sorter: alpha
    api-docs:
      path: /v3/api-docs
    group-configs:
      - group: 'default'
        paths-to-match: '/**'
        packages-to-scan: com.jiang.friendsGatheringBackend.controller
  # knife4j的增强配置，不需要增强可以不配
  knife4j:
    enable: true
    setting:
      language: zh_cn