spring:
  application:
    name: friends-gathering-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=UTC
    username: root
    password: 1234